name: rag
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==23.2.1
  - pip:
    - unstructured[all-docs]
    - langchain
    - openai
    - python-dotenv
    - azure-identity
    - tiktoken
    - semantic_kernel
    - azure-search-documents==11.4.0b9
